
name: tests 
on:
  push:
    branches:
      - master 
      - main
permissions:
  contents: write
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - uses: actions/cache@v2
        with:
          key: ${{ github.ref }}
          path: .cache
      - run: pip install hatch
      - run: hatch run cov
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3


